// GENERATED CODE
// Do not edit this file.

import * as React from "react";
import { HelloRequest, HelloReplay } from "./proto_pb";
import { grpc } from "grpc-web-client";

export declare function createHelloRequest(
  obj: Partial<HelloRequest.AsObject>
): HelloRequest;

export declare function createHelloReplay(
  obj: Partial<HelloReplay.AsObject>
): HelloReplay;

export declare function useSayHello(
  obj: Partial<HelloRequest.AsObject>
): {
  data: HelloReplay.AsObject | undefined;
  response: grpc.UnaryOutput<HelloReplay>;
  isLoading: boolean;
  error: Error | null;
};

export declare function useSayHelloAgain(
  obj: Partial<HelloRequest.AsObject>
): {
  data: HelloReplay.AsObject | undefined;
  response: grpc.UnaryOutput<HelloReplay>;
  isLoading: boolean;
  error: Error | null;
};
